apiVersion: v1
kind: Namespace
metadata:
  name: shadow-idp
  labels:
    name: shadow-idp
    app.kubernetes.io/name: shadow-idp
    app.kubernetes.io/component: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: shadow-idp-system
  labels:
    name: shadow-idp-system
    app.kubernetes.io/name: shadow-idp
    app.kubernetes.io/component: system
