apiVersion: v1
kind: ServiceAccount
metadata:
  name: shadow-idp-service-account
  namespace: shadow-idp
  labels:
    app.kubernetes.io/name: shadow-idp
    app.kubernetes.io/part-of: shadow-idp-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: shadow-idp
  name: shadow-idp-role
  labels:
    app.kubernetes.io/name: shadow-idp
    app.kubernetes.io/part-of: shadow-idp-platform
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shadow-idp-role-binding
  namespace: shadow-idp
  labels:
    app.kubernetes.io/name: shadow-idp
    app.kubernetes.io/part-of: shadow-idp-platform
subjects:
- kind: ServiceAccount
  name: shadow-idp-service-account
  namespace: shadow-idp
roleRef:
  kind: Role
  name: shadow-idp-role
  apiGroup: rbac.authorization.k8s.io
